package com.xworkz.person.association.thing;

public enum StateName {
	KARNATAKA, ANDRAPREDESH, MADYAPREDESH, TAMILNADU, KERALA, GOA, UTTARAPRADESH, RAJASTAN, JAMMU, KASHMIR, assam,
	GUJARAT, PASHIMABANGALA, NEW_DELHI;

}
