package com.xworkz.pizza.constant;

public enum Types {
	SHORT_RANGE_WEAPONS,lONG_RANGE_WEAPONS,FIRAMS,COMBAT_WEPONS,ROCKET,NUCLEAR_WEPONS,BIOLOGICAL_WEPONS,CHEMICAL_WEAPONS,MISSILAS,ROCKETS,SEMI_AUTOMIC
	,SIGE_WEPONS,EXPLOSSIVE,AK47,Long;

}
